### ISSUE TITLE
Source of language datasets

### ISSUE THREAD

**Issue by DonaldTsang** [kent37/guess-language#13]
Where is the source text dataset for the Ngrams of those 64 languages? Would like to see if it is different from https://github.com/wooorm/franc/issues/78 usage of UDHR, and if it is more accurate than them.

**Comment by kent37** [comment]
I don't know, you have to look at the projects this one came from. See the README.

**Comment by DonaldTsang** [comment]
@kent37 
To quote the ReadME
```
Detects over 60 languages - all languages listed in the `trigrams
<http://code.google.com/p/guess-language/source/browse/trunk/guess_language/trigrams/>`_
directory plus Japanese, Chinese, Korean and Greek.
```
But the link itself is broken, which returns to this repo, which makes things a lot more confusing.

**Comment by kent37** [comment]
The trigrams used by guess-language are in  
https://github.com/kent37/guess-language/tree/master/guess_language/trigrams

**Comment by DonaldTsang** [comment]
@kent37 I am referring to the corpus/text that the trigram is derived from, NOT the trigram themselves

**Comment by kent37** [comment]
I have no information about the corpus used.
