### ISSUE TITLE
Python 3 port created 🎉 

### ISSUE THREAD

**Issue by AshwinRaikar88** [kent37/guess-language#15]
Hello @kent37, I've just made a few changes to make it compatible with python 3

The bitbucket links shared were not working 
I'll be glad to share it on my new repo or make a pull request on a separate branch

**Comment by kent37** [comment]
Please share this on your own repo, I am no longer maintaining this package.

**Comment by pawanjenu** [comment]
@AshwinRaikar88 , can you share the repo link?
